### ISSUE TITLE
Error on pip install - ensembleclustering and kahypar dependencies

### ISSUE THREAD

**Issue by nranthony** [burtonrj/CytoCluster#1]
Alas, I get an error on trying to install

```sh
conda create --name flowc python=3.10
conda activate flowc
pip install cytocluster
```

leads to an error:

```
ERROR: Cannot install cytocluster because these package versions have conflicting dependencies.

The conflict is caused by:
    ensembleclustering 1.0.11 depends on kahypar==1.1.3
    ensembleclustering 1.0.1 depends on kahypar==1.1.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

If then try to separately install `kahypar` using 
```sh
pip install kahypar
```
I get the follow errors:

```
Collecting kahypar
  Using cached kahypar-1.0.tar.gz (8.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\nelly\AppData\Local\Temp\pip-install-9bmjaav9\kahypar_17b055a634f5427fab2ec09e4eea68f0\setup.py", line 71, in <module>
          long_description = fh.read()
        File "C:\tools\miniconda3\envs\flowc\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5786: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

Any thoughts much appreciated :)  Thanks in advance for your time.

**Comment by burtonrj** [comment]
Hi @nranthony, I've managed to replicate the issue. It's originating from the `ensembleclustering` library (a fork of `ClusterEnsembles`) which depends on Kahypar 1.1.3; the original author for `ClusterEnsembles` doesn't appear to maintain it anymore and its not on PyPi, so I've forked it (https://github.com/burtonrj/ClusterEnsembles) and made it available as the `ensembleclustering` library.

I get this error when I try `pip install kahypar==1.1.3`:

`ERROR: Could not find a version that satisfies the requirement kahypar==1.1.3 (from versions: 1.0, 1.1.7, 1.1.8)`

I don't think version 1.1.3 is supported anymore. I'll update `ensembleclustering` to use version 1.1.8 asap and hopefully that should resolve these issues.

**Comment by burtonrj** [comment]
New version of `cytocluster` (0.1.13) is now on PyPi. Now depends on Kahypar v1.1.8 and should resolve the issues here. Please feel free to reopen the issue if you have any other problems.

**Comment by nranthony** [comment]
Hi @burtonrj, thanks for the super speedy response.
Alas, I still run into errors.

I completely deleted the env and started over.  I used a new python 3.10 conda environment, and then pip install cytocluster.  This leads to the same set of errors stating that pip hits dependency issues with cytocluster up to and including 0.1.12, but not 0.1.13.  Not sure that pip is pulling the latest version.

Explicitly defining cytocluster==0.1.13 still leads to a dependency error that python should be <3.10.

Deleting the env and using a fresh env with python 3.9 and cytocluster==0.1.13 leaves me with an error:
```
ERROR: Could not find a version that satisfies the requirement kahypar<2.0.0,>=1.1.8 (from ensembleclustering) (from versions: 1.0)
ERROR: No matching distribution found for kahypar<2.0.0,>=1.1.8
```
Looking at PyPi I think I'm seeing that it's not available for Win OS: https://pypi.org/project/kahypar/#files

What OS and python versions are you using?

Thanks

**Comment by burtonrj** [comment]
Hi @nranthony, sorry you're still having issues. I'm running Ubuntu 22.04 and Python 3.10. Can I suggest you try using Linux subsystem for Windows and see if you have the same issue? 

If you still hit problems then let me know, maybe I can create a docker image for you to use. What is the particular use case you have in mind? Will you be using CytoCluster in a Jupyter Notebook for example?

**Comment by nranthony** [comment]
Thanks @burtonrj, setting it up in WSL worked.  Setup the conda env, and needed to add the `build-essential` package to the OS, and all looks good.
Much appreciated :)

**Comment by burtonrj** [comment]
Amazing! Glad it's resolved. I'll add a note to the readme that it requires the Linux subsystem or a Linux docker image to run on windows.
